language: php

php:
  - 7.3

before_script:
  - composer self-update
  - composer install --optimize-autoloader --no-interaction

script:
  - ./vendor/bin/phpunit

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
